services:


  db:
    image: postgres:15
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_POSTGRES_DB}
      - POSTGRES_USER=${DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo_db_data:/var/lib/postgresql/data/pgdata

  # Odoo 17 Application
  odoo:
    build: .
    # image: odoo:18
    env_file: .env
    depends_on:
      - db
    environment:
      - HOST=${ODOO_HOST}
      - USER=${ODOO_USER}
      - PASSWORD=${ODOO_PASSWORD}
      - POSTGRES_DB=${ODOO_POSTGRES_DB}
      - ADMIN_PASSWD=${ODOO_ADMIN_PASSWD}  # Add this line
    ports:
      - "8069:8069"
    volumes:
      - odoo_web_data:/var/lib/odoo
      # - ./config:/etc/odoo
      - ./etc:/etc/odoo
      - ./abd-addons:/mnt/extra-addons
      - ./logs:/var/log/odoo

    restart: unless-stopped
    command: -- --db_host=db --db_user=${ODOO_USER} --db_password=${ODOO_PASSWORD} -u all

  # web:
  #   image: odoo:18.0
  #   depends_on:
  #     - db
  #   ports:
  #     - "8069:8069"
  #   volumes:
  #     - ./addons:/mnt/extra-addons  # Mount your custom addons
  #     - ./etc:/etc/odoo
  #     - odoo_web_data:/var/lib/odoo
  #   environment:
  #     - HOST=db
  #     - USER=odoo
  #     - PASSWORD=odoo_password
  #     - ADMIN_PASSWD=odoo_password  # Add this line
  #   command: --

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: odoo17_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - db

# Named volumes for persistent data
volumes:
  odoo_web_data:
  odoo_db_data:
  pgadmin_data:
