[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = ${ODOO_ADMIN_PASSWD}
db_host = ${DB_HOST}
db_port = ${DB_POSTGRES_PORT}
db_user = ${DB_POSTGRES_USER}
db_password = ${DB_POSTGRES_PASSWORD}
# db_name = odoo
dbfilter = .*
list_db = True
log_level = info
server_wide_modules = base,web